version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.11
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Run Pytest
          command: |
          AWS_ACCESS_KEY_ID = ${AWS_ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY = ${AWS_SECRET_ACCESS_KEY}
          pytest
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  build_test:
    jobs:
      - run_tests